import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { SessionProvider } from "next-auth/react";
import LayoutProviders from "./_components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<LayoutProviders>
					<div className="container bg-amber-100 h-[100vh] w-[100vw]">
						<Navbar />
						<div className="content mx-auto text-center p-5">
							{children}
						</div>
					</div>
				</LayoutProviders>
			</body>
		</html>
	);
}
